Rewiw
whrgs/ono-tebe-nado pull request #5
Opened 2024-07-30 11:41 UTC by whrgs

2024-07-30 13:20 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Здравствуйте!  У вас получилась хорошая работа!

_Что понравилось:_

- Хорошая структура HTML
- нет скролла от 1100px и более и все элементы отображаются корректно
- Хорошее форматирование документа
- хорошие стили
- используется семантика
- Используются списки


_Что необходимо исправить:_

- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- pull request финального варианта, который отправляется на ревью должен быть в ветку, где либо ничего нет, либо только стартовый набор. Сейчас в частях кода нет возможности оставить комментарии https://disk.yandex.ru/i/FIAavLe1Uth4XQ



- https://disk.yandex.ru/i/23mCditSJBl38w при ширине больше чем в макете контент должен быть по центру страницы


- Несоответствия макету:
    - https://disk.yandex.ru/i/Tmv4PUY_fFJrtg выравнивание элементов
    - https://disk.yandex.ru/i/1WBQ7jSd94jCtw  выравнивание элементов
    - https://disk.yandex.ru/i/fkLHFiK1F1WPQw выравнивание элементов




_Что можно улучшить:_

- Все комментарии "Можно лучше"

- Селекторы в файле стилей должны располагаться в порядке их появления в html

- В любом месте в файлах CSS в проекте(кроме самого CSS файла подключения шрифтов, где указывается только название подключаемого шрифта), где указано свойство  `font-family`  помимо основного шрифта так же должен быть указан альтернативный шрифт и тип засечек. Это делается для того, что если по каким-то причинами основной шрифт не загрузится, то внешний вид страницы не будет изменен очень сильно.  Порядок написания шрифтов: Основной шрифт, [Веб-безопасный альтернативный шрифт(по ссылке список этих шрифтов)](https://www.cssfontstack.com/), Тип засечек. Пример ` font-family: Inter, Arial, sans-serif; ` 

- Желательно использовать все классы по БЭМ. 
  - https://ru.bem.info/methodology/quick-start/
  - Проверить ошибки БЭМ можно на  https://nglazov.github.io/bem-validator-page/
  - струтуру можно проверить на https://yoksel.github.io/html-tree/

- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- Для более точной корректировки размеров текстов и расстояний между элементами можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi) для Chrome 


**Напоминание:** После выполнения всех критических замечаний работа будет принята. Предложения по улучшению выполняются по желанию.

Желаю успеха!

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
>      justify-content: space-between;
---

**Можно лучше:**
Строка 113: 
Или вместо координат в данном случае можно использовать свойство  ` inset: 0; `, так как отступы от всех краёв родительского элемента нулевые

Примеры и варианты значений этого свойства можно посмотреть поискав по названию свойства на

-  https://doka.guide/
-  https://developer.mozilla.org/ru/



---

**Нужно исправить - 101:**
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding)   отступы для соответствия макету.
 
  
  не следует жестко ограничивать высоту блока внутри которого есть какое то содержимое. Размер, количество элементов или количество текста внутри может измениться и при задании фиксированной высоты эти элементы могут "выпасть" из блока, тем самым сломав верстку. 
Поэтому вместо `height` нужно задать такие внутренние отступы (padding) для блока, что бы суммарно с высотой контента блок имел требуемую высоту. 
Это позволит при необходимости адаптироваться блоку по высоте под свое содержимое
Иногда для блоков  без содержимого или для блоков с фоновым изображением может потребоваться так же задание `min-height` которое не позволяет ужиматься блоку меньше определенной высоты даже в том случае если в нем будет мало контента.

---

**Нужно исправить - 81, 376:**


Используйте max-width, что бы при меньшей ширине контента контейнер не занимал больше места

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
> +    height: 105px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding)   отступы для соответствия макету.
  
  ---
  
  не следует жестко ограничивать высоту блока внутри которого есть какое то содержимое. Размер, количество элементов или количество текста внутри может измениться и при задании фиксированной высоты эти элементы могут "выпасть" из блока, тем самым сломав верстку. 
Поэтому вместо `height` нужно задать такие внутренние отступы (padding) для блока, что бы суммарно с высотой контента блок имел требуемую высоту. 
Это позволит при необходимости адаптироваться блоку по высоте под свое содержимое
Иногда для блоков  без содержимого или для блоков с фоновым изображением может потребоваться так же задание `min-height` которое не позволяет ужиматься блоку меньше определенной высоты даже в том случае если в нем будет мало контента.

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
>      height: 595px;
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
>    }
---

**Нужно исправить - 325:**
**Высоту нужно удалить** Тут она не требуется. Используйте внутренние (padding) и внешние (margin) отступы для соответствия макету.

2024-07-30 13:20 UTC, Avaakum commented on index.html
> +    <link rel="stylesheet" href="./styles/global.css" >
---

**Отлично:**

Правильный порядок подключения стилей. Шрифты должны быть подключены первыми, потом общие стили(сброс), потом кастомные. При таком порядке подключении шрифты могут быть использованы в двух последующих файлах.  А так же сброс стилей должен быть до подключения своих стилей из-за специфики CSS, чтобы `global.css` не переопределил никаких наших стилей.

2024-07-30 13:20 UTC, Avaakum commented on index.html
>       <a class="header__logo">
---

**Отлично:**

Логотип должен быть ссылкой без атрибута href(что бы по ссылке не было перехода)  для улучшения семантики страницы.

2024-07-30 13:20 UTC, Avaakum commented on index.html
>          <span class="header__logo-image"> </span>
Лишний элемент

2024-07-30 13:20 UTC, Avaakum commented on index.html
>          <address class="header__address">
- элементы address однотипны в стилизации в header и footer, нужен одинаковый класс без привязки к типу размещения блока

2024-07-30 13:20 UTC, Avaakum commented on index.html
>        <section class="about">
---

**Отлично - 68:**
Отличная семантика и структура

2024-07-30 13:20 UTC, Avaakum commented on index.html
---

**Можно лучше - 139:**
- Для улучшения семантики этого блока можно использовать тег `<article>` 

 - https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

2024-07-30 13:20 UTC, Avaakum commented on index.html
>          <ul class="footer__social-list">
---

**Можно лучше:**

Можно использовать для обертки списка ссылок тег `<nav>`, можно даже без класса, только для семантики.
Этим элементом принято выделять список из ссылок, отвечающий за навигацию по сайту и не только. Добавление этого элемента улучшает восприятие вашей верстки поисковыми машинами, а так же скринридерами. 
Можно использовать несколько тегов `nav` в проекте.

https://doka.guide/html/nav/#alyona-batickaya-sovetuet

2024-07-30 13:20 UTC, Avaakum commented on index.html
>            <li class="footer__social-list-item">
---

**Отлично:**

Отлично, использован список для повторяющихся элементов

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
>    .header {
---

**Можно лучше:**

 header для выравнивания удобно использовать грид. Ячейки по краям будут занимать ширину по одному фрагменту, а логотип только ширину равную минимальной ширине контента (min-content) ` 
    grid-template-columns: 1fr min-content 1fr; `  .  
  
  А для выравнивания внутри грид-ячейки в таких случаях удобно использовать

- https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self
- https://developer.mozilla.org/ru/docs/Web/CSS/align-self

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
---

**Нужно исправить - 219:**
- https://disk.yandex.ru/i/GD3cMR_vE9vGAA Используйте свойство gap между элементами списка для задания отступ, что бы при добавлении новых карточек такой же отступ между ними был и по горизонтали

2024-07-30 13:20 UTC, Avaakum commented on styles/style.css
>      text-underline-offset: 5px;
---

**Можно лучше:**

Нужно ограничить максимальную ширину ссылки в соответствии с контентом, значение `fit-content` или изменить выравнивание элемента, чтобы он не занимал больше пространства, чем внутренний контент. Сейчас ссылка занимает всю ширину родителя и может быть нажата в пустом месте.

https://developer.mozilla.org/ru/docs/Web/CSS/max-width

2024-07-31 07:26 UTC, merged

2024-07-31 07:42 UTC, whrgs reviewed
я сделала изменения, но не понимаю появились ли они тут, потому что в истории не показываются

2024-07-31 13:55 UTC, Avaakum reviewed
Развернуть общий комментарий ⬇︎

Здравствуйте. К сожалению проект отклоняется от проверки. Итерация не теряется. 

- _На повторных итерациях не исправлены критические замечания._ 
    - **Пример:** 
       - Начиная с неисправленных пунктов в общем комментарии https://disk.yandex.ru/i/QxY5kl1QxacQkw  в ревью предыдущей итерации нужно проверить исправление **всех критических комментариев** в работе. Пожалуйста, в первую очередь создайте новую пустую ветку в git и потом сделайте туда пул реквест из ветки, где происходило создание проекта и уже отправляйте ссылку на этот пул реквест, что бы была возможность оставлять комментарии в коде.  Если у вас есть сомнения по поводу того, что комментарий исправлен, то, пожалуйста, перечитайте комментарии внимательно, там описано, что нужно исправить в работе. Если что-то исправить не получается, то можно смело обращаться к наставнику, он сможет подсказать. Чтобы исправить ошибки валидатора(при наличии), можно в chrome перевести страницу на русский, чтобы было понятнее, что именно за ошибки он выдаёт. А для соответствия макету можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi  )  для Chrome.



     - Пожалуйста, будьте внимательны, проверяйте, исправляйте и присылайте работу только после исправления **всех критических замечаний** c предыдущей итерации
    - Если у вас есть технические проблемы, то попробуйте обратиться в поддержку или спросить в чате студентов не было ли у кого похожих случаев.



_Вне счета итераций(без исправления **критических ошибок** работу не сдать):_

- Для соответствия макету в хедере нужно удалить лишнюю ширину и подправить отступы margin от краёв
- Для соответствия макету в футере нужно подправить отступ над ним, что бы отступ между контактной информацией и текстом в секции выше был по пиксель перфект. Потом выровнять элементы в футере по горизонтали по верху этих элементов, а не по центру, и потом подправить отступы между ссылками-логотипами.